### ISSUE TITLE
Missing the order 65

### ISSUE THREAD

**Issue by chihchunhsu** [Keck-DataReductionPipelines/NIRSPEC-Data-Reduction-Pipeline#6]
When reducing the private data in the N3 band, the order 65 is missing, and this problem is repeating for at least two different observations. There is no information of the order 65 in the log files. Both of the reduced data products have the orders 55-64 and 66.

**Comment by jmader** [comment]
@chihchunhsu Can you let me know the UT date and file names of the observations you are reducing?

**Comment by chihchunhsu** [comment]
They are:
UTC     = '13:37:46.81' FILENAME= 'nov16s0064.fits'
UTC     = '13:38:28.11 ' FILENAME= 'nov16s0065.fits'
UTC     = '13:49:02.12' FILENAME= 'nov16s0067.fits'
UTC     = '14:01:54.62' FILENAME= 'nov16s0068.fits'

UTC     = '07:29:27.79' FILENAME= 'feb06s0091.fits'
UTC     = '07:33:15.39' FILENAME= 'feb06s0092.fits'
UTC     = '07:36:46.94' FILENAME= 'feb06s0093.fits'
UTC     = '07:40:32.89' FILENAME= 'feb06s0094.fits'

Thanks!

**Comment by Astrodude11** [comment]
@chihchunhsu NSDRP processes orders in descending fashion. If an order is determined to be off the detector then it assumes the previous one is the last one. So in your case, order 65 seems to have been located but not reduced. I'd be curious to know whether the -verbose flag provides any clues as to why order 65 was skipped...

Also, the -debug flag will write more detailed information to the log.

**Comment by Astrodude11** [comment]
@chihchunhsu Use the -spatial_jump_override flag and order 65 will be reduced successfully. In short, refer to page 28 and 43 in the software design document. I can give a more detailed explanation if you wish.

**Comment by chihchunhsu** [comment]
@Astrodude11 Thank you! By using the flag, the order 65 is successfully reduced.
