### ISSUE TITLE
Couldn't reduce the data on 2014/04/12

### ISSUE THREAD

**Issue by chihchunhsu** [Keck-DataReductionPipelines/NIRSPEC-Data-Reduction-Pipeline#9]
I couldn't reduce the data on 2014/04/12 (PI: Burgasser). On the log, it says: 

WARNING - reduce_frame.py:190 - failed to reduce order 32: cannot find spatial profile for frame A order 32

and

INFO - reduce_frame.py:268 - n sky lines identified = 0

There are reduced data on the KOA, so I was wondering if I missed any steps that are crucial. I used "-spatial_jump_override" and "-debug" in the KOA mode.

Thanks for your time!

**Comment by jmader** [comment]
Please try your reduction without the -spatial_jump_override option.  

python /path/to/nsdrp.py in_dir out_dir -oh_filename /path/to/ir_ohlines.dat -debug

**Comment by chihchunhsu** [comment]
It worked! Thank you so much.
